services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./templates:/app/templates
      - ./garbage_resnet50_final_model.pth:/app/garbage_resnet50_final_model.pth
    restart: unless-stopped